/* generated configuration header file - do not edit */
#ifndef BSP_IRQ_CFG_H_
#define BSP_IRQ_CFG_H_
#define BSP_IRQ_CFG_ADC0_SCAN_END (BSP_IRQ_DISABLED) /* ADC0 SCAN END: Disabled */
#define BSP_IRQ_CFG_ADC0_SCAN_END_B (BSP_IRQ_DISABLED) /* ADC0 SCAN END B: Disabled */
#define BSP_IRQ_CFG_ADC0_WINDOW_A (BSP_IRQ_DISABLED) /* ADC0 WINDOW A: Disabled */
#define BSP_IRQ_CFG_ADC0_WINDOW_B (BSP_IRQ_DISABLED) /* ADC0 WINDOW B: Disabled */
#define BSP_IRQ_CFG_ADC0_COMPARE_MATCH (BSP_IRQ_DISABLED) /* ADC0 COMPARE MATCH: Disabled */
#define BSP_IRQ_CFG_ADC0_COMPARE_MISMATCH (BSP_IRQ_DISABLED) /* ADC0 COMPARE MISMATCH: Disabled */
#define BSP_IRQ_CFG_AES_WRREQ (BSP_IRQ_DISABLED) /* AES WRREQ: Disabled */
#define BSP_IRQ_CFG_AES_RDREQ (BSP_IRQ_DISABLED) /* AES RDREQ: Disabled */
#define BSP_IRQ_CFG_AGT0_INT (3) /* AGT0 INT: Priority 3 (lowest, not valid if using ThreadX) */
#define BSP_IRQ_CFG_AGT0_COMPARE_A (BSP_IRQ_DISABLED) /* AGT0 COMPARE A: Disabled */
#define BSP_IRQ_CFG_AGT0_COMPARE_B (BSP_IRQ_DISABLED) /* AGT0 COMPARE B: Disabled */
#define BSP_IRQ_CFG_AGT1_INT (BSP_IRQ_DISABLED) /* AGT1 INT: Disabled */
#define BSP_IRQ_CFG_AGT1_COMPARE_A (BSP_IRQ_DISABLED) /* AGT1 COMPARE A: Disabled */
#define BSP_IRQ_CFG_AGT1_COMPARE_B (BSP_IRQ_DISABLED) /* AGT1 COMPARE B: Disabled */
#define BSP_IRQ_CFG_CAC_FREQUENCY_ERROR (BSP_IRQ_DISABLED) /* CAC FREQUENCY ERROR: Disabled */
#define BSP_IRQ_CFG_CAC_MEASUREMENT_END (BSP_IRQ_DISABLED) /* CAC MEASUREMENT END: Disabled */
#define BSP_IRQ_CFG_CAC_OVERFLOW (BSP_IRQ_DISABLED) /* CAC OVERFLOW: Disabled */
#define BSP_IRQ_CFG_CAN0_ERROR (BSP_IRQ_DISABLED) /* CAN0 ERROR: Disabled */
#define BSP_IRQ_CFG_CAN0_FIFO_RX (BSP_IRQ_DISABLED) /* CAN0 FIFO RX: Disabled */
#define BSP_IRQ_CFG_CAN0_FIFO_TX (BSP_IRQ_DISABLED) /* CAN0 FIFO TX: Disabled */
#define BSP_IRQ_CFG_CAN0_MAILBOX_RX (BSP_IRQ_DISABLED) /* CAN0 MAILBOX RX: Disabled */
#define BSP_IRQ_CFG_CAN0_MAILBOX_TX (BSP_IRQ_DISABLED) /* CAN0 MAILBOX TX: Disabled */
#define BSP_IRQ_CFG_CGC_MOSC_STOP (BSP_IRQ_DISABLED) /* CGC MOSC STOP: Disabled */
#define BSP_IRQ_CFG_COMP_LP_0 (BSP_IRQ_DISABLED) /* COMP LP 0: Disabled */
#define BSP_IRQ_CFG_COMP_LP_1 (BSP_IRQ_DISABLED) /* COMP LP 1: Disabled */
#define BSP_IRQ_CFG_CTSU_WRITE (BSP_IRQ_DISABLED) /* CTSU WRITE: Disabled */
#define BSP_IRQ_CFG_CTSU_READ (BSP_IRQ_DISABLED) /* CTSU READ: Disabled */
#define BSP_IRQ_CFG_CTSU_END (BSP_IRQ_DISABLED) /* CTSU END: Disabled */
#define BSP_IRQ_CFG_DOC_INT (BSP_IRQ_DISABLED) /* DOC INT: Disabled */
#define BSP_IRQ_CFG_DTC_COMPLETE (BSP_IRQ_DISABLED) /* DTC COMPLETE: Disabled */
#define BSP_IRQ_CFG_DTC_END (BSP_IRQ_DISABLED) /* DTC END: Disabled */
#define BSP_IRQ_CFG_ELC_SOFTWARE_EVENT_0 (BSP_IRQ_DISABLED) /* ELC SOFTWARE EVENT 0: Disabled */
#define BSP_IRQ_CFG_ELC_SOFTWARE_EVENT_1 (BSP_IRQ_DISABLED) /* ELC SOFTWARE EVENT 1: Disabled */
#define BSP_IRQ_CFG_FCU_FRDYI (1) /* FCU FRDYI: Priority 1 */
#define BSP_IRQ_CFG_GPT0_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT0 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT0_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT0 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT0_COMPARE_C (BSP_IRQ_DISABLED) /* GPT0 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT0_COMPARE_D (BSP_IRQ_DISABLED) /* GPT0 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT0_COUNTER_OVERFLOW (2) /* GPT0 COUNTER OVERFLOW: Priority 2 */
#define BSP_IRQ_CFG_GPT0_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT0 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT1_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT1 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT1_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT1 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT1_COMPARE_C (BSP_IRQ_DISABLED) /* GPT1 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT1_COMPARE_D (BSP_IRQ_DISABLED) /* GPT1 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT1_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT1 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT1_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT1 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT2_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT2 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT2_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT2 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT2_COMPARE_C (BSP_IRQ_DISABLED) /* GPT2 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT2_COMPARE_D (BSP_IRQ_DISABLED) /* GPT2 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT2_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT2 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT2_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT2 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT3_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT3 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT3_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT3 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT3_COMPARE_C (BSP_IRQ_DISABLED) /* GPT3 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT3_COMPARE_D (BSP_IRQ_DISABLED) /* GPT3 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT3_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT3 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT3_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT3 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT4_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT4 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT4_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT4 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT4_COMPARE_C (BSP_IRQ_DISABLED) /* GPT4 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT4_COMPARE_D (BSP_IRQ_DISABLED) /* GPT4 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT4_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT4 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT4_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT4 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT5_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT5 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT5_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT5 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT5_COMPARE_C (BSP_IRQ_DISABLED) /* GPT5 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT5_COMPARE_D (BSP_IRQ_DISABLED) /* GPT5 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT5_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT5 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT5_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT5 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT6_CAPTURE_COMPARE_A (BSP_IRQ_DISABLED) /* GPT6 CAPTURE COMPARE A: Disabled */
#define BSP_IRQ_CFG_GPT6_CAPTURE_COMPARE_B (BSP_IRQ_DISABLED) /* GPT6 CAPTURE COMPARE B: Disabled */
#define BSP_IRQ_CFG_GPT6_COMPARE_C (BSP_IRQ_DISABLED) /* GPT6 COMPARE C: Disabled */
#define BSP_IRQ_CFG_GPT6_COMPARE_D (BSP_IRQ_DISABLED) /* GPT6 COMPARE D: Disabled */
#define BSP_IRQ_CFG_GPT6_COUNTER_OVERFLOW (BSP_IRQ_DISABLED) /* GPT6 COUNTER OVERFLOW: Disabled */
#define BSP_IRQ_CFG_GPT6_COUNTER_UNDERFLOW (BSP_IRQ_DISABLED) /* GPT6 COUNTER UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ0 (BSP_IRQ_DISABLED) /* ICU IRQ0: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ1 (BSP_IRQ_DISABLED) /* ICU IRQ1: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ2 (BSP_IRQ_DISABLED) /* ICU IRQ2: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ3 (BSP_IRQ_DISABLED) /* ICU IRQ3: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ4 (BSP_IRQ_DISABLED) /* ICU IRQ4: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ5 (BSP_IRQ_DISABLED) /* ICU IRQ5: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ6 (BSP_IRQ_DISABLED) /* ICU IRQ6: Disabled */
#define BSP_IRQ_CFG_ICU_IRQ7 (BSP_IRQ_DISABLED) /* ICU IRQ7: Disabled */
#define BSP_IRQ_CFG_ICU_SNOOZE_CANCEL (BSP_IRQ_DISABLED) /* ICU SNOOZE CANCEL: Disabled */
#define BSP_IRQ_CFG_IIC0_RXI (BSP_IRQ_DISABLED) /* IIC0 RXI: Disabled */
#define BSP_IRQ_CFG_IIC0_TXI (BSP_IRQ_DISABLED) /* IIC0 TXI: Disabled */
#define BSP_IRQ_CFG_IIC0_TEI (BSP_IRQ_DISABLED) /* IIC0 TEI: Disabled */
#define BSP_IRQ_CFG_IIC0_ERI (BSP_IRQ_DISABLED) /* IIC0 ERI: Disabled */
#define BSP_IRQ_CFG_IIC0_WUI (BSP_IRQ_DISABLED) /* IIC0 WUI: Disabled */
#define BSP_IRQ_CFG_IIC1_RXI (BSP_IRQ_DISABLED) /* IIC1 RXI: Disabled */
#define BSP_IRQ_CFG_IIC1_TXI (BSP_IRQ_DISABLED) /* IIC1 TXI: Disabled */
#define BSP_IRQ_CFG_IIC1_TEI (BSP_IRQ_DISABLED) /* IIC1 TEI: Disabled */
#define BSP_IRQ_CFG_IIC1_ERI (BSP_IRQ_DISABLED) /* IIC1 ERI: Disabled */
#define BSP_IRQ_CFG_IOPORT_EVENT_1 (BSP_IRQ_DISABLED) /* IOPORT EVENT 1: Disabled */
#define BSP_IRQ_CFG_IOPORT_EVENT_2 (BSP_IRQ_DISABLED) /* IOPORT EVENT 2: Disabled */
#define BSP_IRQ_CFG_IWDT_UNDERFLOW (BSP_IRQ_DISABLED) /* IWDT UNDERFLOW: Disabled */
#define BSP_IRQ_CFG_KEY_INT (BSP_IRQ_DISABLED) /* KEY INT: Disabled */
#define BSP_IRQ_CFG_LPM_SNOOZE_REQUEST (BSP_IRQ_DISABLED) /* LPM SNOOZE REQUEST: Disabled */
#define BSP_IRQ_CFG_LVD_LVD1 (BSP_IRQ_DISABLED) /* LVD LVD1: Disabled */
#define BSP_IRQ_CFG_LVD_LVD2 (BSP_IRQ_DISABLED) /* LVD LVD2: Disabled */
#define BSP_IRQ_CFG_OPS_UVW_EDGE (BSP_IRQ_DISABLED) /* OPS UVW EDGE: Disabled */
#define BSP_IRQ_CFG_POEG0_EVENT (BSP_IRQ_DISABLED) /* POEG0 EVENT: Disabled */
#define BSP_IRQ_CFG_POEG1_EVENT (BSP_IRQ_DISABLED) /* POEG1 EVENT: Disabled */
#define BSP_IRQ_CFG_RTC_ALARM (BSP_IRQ_DISABLED) /* RTC ALARM: Disabled */
#define BSP_IRQ_CFG_RTC_PERIOD (BSP_IRQ_DISABLED) /* RTC PERIOD: Disabled */
#define BSP_IRQ_CFG_RTC_CARRY (BSP_IRQ_DISABLED) /* RTC CARRY: Disabled */
#define BSP_IRQ_CFG_SCI0_RXI (2) /* SCI0 RXI: Priority 2 */
#define BSP_IRQ_CFG_SCI0_TXI (2) /* SCI0 TXI: Priority 2 */
#define BSP_IRQ_CFG_SCI0_TEI (2) /* SCI0 TEI: Priority 2 */
#define BSP_IRQ_CFG_SCI0_ERI (2) /* SCI0 ERI: Priority 2 */
#define BSP_IRQ_CFG_SCI0_AM (BSP_IRQ_DISABLED) /* SCI0 AM: Disabled */
#define BSP_IRQ_CFG_SCI0_RXI_OR_ERI (BSP_IRQ_DISABLED) /* SCI0 RXI OR ERI: Disabled */
#define BSP_IRQ_CFG_SCI1_RXI (BSP_IRQ_DISABLED) /* SCI1 RXI: Disabled */
#define BSP_IRQ_CFG_SCI1_TXI (BSP_IRQ_DISABLED) /* SCI1 TXI: Disabled */
#define BSP_IRQ_CFG_SCI1_TEI (BSP_IRQ_DISABLED) /* SCI1 TEI: Disabled */
#define BSP_IRQ_CFG_SCI1_ERI (BSP_IRQ_DISABLED) /* SCI1 ERI: Disabled */
#define BSP_IRQ_CFG_SCI1_AM (BSP_IRQ_DISABLED) /* SCI1 AM: Disabled */
#define BSP_IRQ_CFG_SCI9_RXI (1) /* SCI9 RXI: Priority 1 */
#define BSP_IRQ_CFG_SCI9_TXI (1) /* SCI9 TXI: Priority 1 */
#define BSP_IRQ_CFG_SCI9_TEI (1) /* SCI9 TEI: Priority 1 */
#define BSP_IRQ_CFG_SCI9_ERI (1) /* SCI9 ERI: Priority 1 */
#define BSP_IRQ_CFG_SCI9_AM (BSP_IRQ_DISABLED) /* SCI9 AM: Disabled */
#define BSP_IRQ_CFG_SPI0_RXI (BSP_IRQ_DISABLED) /* SPI0 RXI: Disabled */
#define BSP_IRQ_CFG_SPI0_TXI (BSP_IRQ_DISABLED) /* SPI0 TXI: Disabled */
#define BSP_IRQ_CFG_SPI0_IDLE (BSP_IRQ_DISABLED) /* SPI0 IDLE: Disabled */
#define BSP_IRQ_CFG_SPI0_ERI (BSP_IRQ_DISABLED) /* SPI0 ERI: Disabled */
#define BSP_IRQ_CFG_SPI0_TEI (BSP_IRQ_DISABLED) /* SPI0 TEI: Disabled */
#define BSP_IRQ_CFG_SPI1_RXI (BSP_IRQ_DISABLED) /* SPI1 RXI: Disabled */
#define BSP_IRQ_CFG_SPI1_TXI (BSP_IRQ_DISABLED) /* SPI1 TXI: Disabled */
#define BSP_IRQ_CFG_SPI1_IDLE (BSP_IRQ_DISABLED) /* SPI1 IDLE: Disabled */
#define BSP_IRQ_CFG_SPI1_ERI (BSP_IRQ_DISABLED) /* SPI1 ERI: Disabled */
#define BSP_IRQ_CFG_SPI1_TEI (BSP_IRQ_DISABLED) /* SPI1 TEI: Disabled */
#define BSP_IRQ_CFG_TRNG_RDREQ (BSP_IRQ_DISABLED) /* TRNG RDREQ: Disabled */
#define BSP_IRQ_CFG_USBFS_INT (BSP_IRQ_DISABLED) /* USBFS INT: Disabled */
#define BSP_IRQ_CFG_USBFS_RESUME (BSP_IRQ_DISABLED) /* USBFS RESUME: Disabled */
#define BSP_IRQ_CFG_WDT_UNDERFLOW (BSP_IRQ_DISABLED) /* WDT UNDERFLOW: Disabled */
#endif /* BSP_IRQ_CFG_H_ */
